"use client";

import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Download, FileText, Plus } from "lucide-react";
import { api } from "@/lib/mock/api";
import { useSiriusUser } from "@/lib/providers";
import { can } from "@/lib/constants";
import { PageHeader } from "@/components/ui/PageHeader";
import { Button, Card, Label, Select, Spinner } from "@/components/ui/primitives";
import { Modal } from "@/components/ui/Badge";
import { downloadText, formatDate, timeAgo } from "@/lib/utils";
import type { Report } from "@/types";

const TYPE_META: Record<Report["type"], { label: string; blurb: string }> = {
  executive: { label: "Executive summary", blurb: "Board-ready posture, risk trends and money-at-risk" },
  technical: { label: "Technical", blurb: "Full finding detail with evidence and remediation steps" },
  compliance: { label: "Compliance pack", blurb: "Control-by-control evidence for auditors" },
};

export default function ReportsPage() {
  const user = useSiriusUser();
  const [reports, setReports] = useState<Report[] | null>(null);
  const [modal, setModal] = useState(false);
  const [type, setType] = useState<Report["type"]>("executive");
  const [frameworks, setFrameworks] = useState<string[]>(["pci"]);
  const [range, setRange] = useState("30");
  const [busy, setBusy] = useState(false);

  const create = can(user?.role, "reports:create");

  async function refresh() {
    setReports(await api.reports.list());
  }

  useEffect(() => {
    refresh();
    const t = setInterval(refresh, 4000); // pick up generating → ready transitions
    return () => clearInterval(t);
  }, []);

  async function generate() {
    setBusy(true);
    try {
      const to = new Date();
      const from = new Date(Date.now() - Number(range) * 864e5);
      const r = await api.reports.create(
        {
          type,
          frameworks: type === "compliance" ? frameworks : [],
          from: from.toISOString(),
          to: to.toISOString(),
          name: `${TYPE_META[type].label} · ${to.toLocaleDateString("en-US", { month: "long" })}`,
        },
        user?.name ?? "You"
      );
      toast.success("Report generating — it will appear here when ready");
      setModal(false);
      void r;
    } finally {
      setBusy(false);
    }
  }

  async function download(r: Report) {
    const summary = await api.risk.summary();
    const fws = await api.compliance.frameworks();
    const findings = await api.findings.list();
    const fwNames = (r.frameworks.length ? fws.filter((f) => r.frameworks.includes(f.id)) : fws).map((f) => `${f.name} ${f.version}: ${f.score}%`).join("<br/>");
    const rows = findings
      .slice(0, 20)
      .map((f) => `<tr><td>${f.key}</td><td>${f.title}</td><td>${f.severity}</td><td>${f.status}</td><td>$${f.moneyAtRisk.toLocaleString()}</td></tr>`)
      .join("");
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>${r.name}</title>
<style>body{font-family:system-ui;max-width:860px;margin:40px auto;color:#0f172a}h1{border-bottom:2px solid #22d3ee;padding-bottom:8px}table{border-collapse:collapse;width:100%;font-size:13px}td,th{border:1px solid #e2e8f0;padding:6px 10px;text-align:left}.meta{color:#64748b}</style>
</head><body>
<h1>Sirius Line — ${r.name}</h1>
<p class="meta">${r.type} report · ${formatDate(r.from)} → ${formatDate(r.to)} · generated ${formatDate(r.createdAt)} by ${r.createdBy}</p>
<h2>Executive summary</h2>
<p>Money at risk: <b>$${summary.moneyAtRisk.toLocaleString()}</b> across ${summary.openCount} open findings (MTTR ${summary.mttrDays} days).</p>
<h2>Compliance posture</h2><p>${fwNames}</p>
<h2>Findings</h2>
<table><tr><th>Key</th><th>Title</th><th>Severity</th><th>Status</th><th>$ at risk</th></tr>${rows}</table>
<p class="meta">Generated by Sirius Line · siriusline.io</p></body></html>`;
    downloadText(`${r.name.replace(/\s+/g, "-").toLowerCase()}.html`, html);
  }

  if (!reports) return <Spinner className="min-h-[60vh]" />;

  return (
    <div>
      <PageHeader
        title="Reports"
        subtitle="Board packs, technical deep-dives and audit-ready evidence — generated from live data"
        actions={
          create && (
            <Button onClick={() => setModal(true)}>
              <Plus size={15} /> Generate report
            </Button>
          )
        }
      />

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        {reports.map((r) => (
          <Card key={r.id} className="flex items-center gap-4">
            <span className="rounded-xl bg-accent/10 p-3 text-accent">
              <FileText size={18} />
            </span>
            <div className="min-w-0 flex-1">
              <p className="font-medium text-zinc-200">{r.name}</p>
              <p className="text-xs text-zinc-500">
                {TYPE_META[r.type].label} · {formatDate(r.from)} → {formatDate(r.to)} · by {r.createdBy} · {timeAgo(r.createdAt)}
              </p>
            </div>
            {r.status === "generating" ? (
              <span className="flex items-center gap-2 text-xs text-accent">
                <span className="h-3 w-3 animate-spin rounded-full border-2 border-accent/30 border-t-gold" /> Generating…
              </span>
            ) : (
              <Button size="sm" variant="secondary" onClick={() => download(r)}>
                <Download size={13} /> {r.sizeKb} KB
              </Button>
            )}
          </Card>
        ))}
      </div>

      <Modal open={modal} onClose={() => setModal(false)} title="Generate a report" subtitle="Rendered from your live findings and compliance data.">
        <div className="space-y-4">
          <div>
            <Label>Report type</Label>
            <div className="space-y-2">
              {(Object.keys(TYPE_META) as Report["type"][]).map((t) => (
                <button
                  key={t}
                  onClick={() => setType(t)}
                  className={`w-full rounded-xl border px-3.5 py-2.5 text-left transition ${type === t ? "border-accent/50 bg-accent/10" : "border-line hover:bg-white/[0.03]"}`}
                >
                  <p className={`text-sm font-medium ${type === t ? "text-accent" : "text-zinc-200"}`}>{TYPE_META[t].label}</p>
                  <p className="mt-0.5 text-xs text-zinc-500">{TYPE_META[t].blurb}</p>
                </button>
              ))}
            </div>
          </div>
          {type === "compliance" && (
            <div>
              <Label>Frameworks</Label>
              <div className="flex flex-wrap gap-2">
                {["pci", "soc2", "iso", "gdpr", "nist"].map((f) => {
                  const on = frameworks.includes(f);
                  return (
                    <button
                      key={f}
                      onClick={() => setFrameworks((prev) => (on ? prev.filter((x) => x !== f) : [...prev, f]))}
                      className={`rounded-lg border px-3 py-1.5 text-xs font-medium uppercase transition ${on ? "border-accent/50 bg-accent/10 text-accent" : "border-line text-zinc-400 hover:bg-white/[0.03]"}`}
                    >
                      {f}
                    </button>
                  );
                })}
              </div>
            </div>
          )}
          <div>
            <Label>Date range</Label>
            <Select value={range} onChange={(e) => setRange(e.target.value)}>
              <option value="7">Last 7 days</option>
              <option value="30">Last 30 days</option>
              <option value="90">Last quarter</option>
            </Select>
          </div>
          <Button onClick={generate} loading={busy} className="w-full">
            <FileText size={15} /> Generate
          </Button>
        </div>
      </Modal>
    </div>
  );
}
