/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scans */
        get: operations["listScans"];
        put?: never;
        /** Create a scan */
        post: operations["createScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        /**
         * Scan status
         * @description Also the polling fallback when the WebSocket stream is unavailable —
         *     the PRD's risk register calls WS instability a demo-stage risk.
         */
        get: operations["getScan"];
        put?: never;
        post?: never;
        /** Cancel a scan */
        delete: operations["cancelScan"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        /** Findings for a scan (paginated) */
        get: operations["getScanResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        /** Signed compliance report */
        get: operations["getScanReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{id}/findings/{fid}/fix": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ScanId"];
                fid: components["parameters"]["FindingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a Cerebus fix suggestion
         * @description Core forwards to the worker, which invokes Cerebus: a quarantined model
         *     picks an `action` from a closed vocabulary, a deterministic builder
         *     renders the diff from a template, and a verifier re-runs the original
         *     detection rule against the patched snippet. The rule, not the model, is
         *     the ground truth.
         */
        post: operations["requestFix"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{id}/findings/{fid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ScanId"];
                fid: components["parameters"]["FindingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Triage a finding
         * @description Record a human decision about a finding.
         *
         *     x-decision: D-015 — the PRD lists this endpoint as "accept/dismiss/suppress"
         *     but never gives it a body, and the `findings` DDL has only a `suppressed`
         *     boolean with no column for the other two states. This defines a
         *     `triage_state` so the three verbs are distinguishable and auditable;
         *     `suppressed` stays derived from `triage_state == "suppressed"`.
         */
        patch: operations["triageFinding"];
        trace?: never;
    };
    "/scans/{id}/findings/{fid}/validate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ScanId"];
                fid: components["parameters"]["FindingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Opt-in live secret validity check
         * @description Makes a rate-limited, **read-only** call to the provider (e.g. GET
         *     https://api.stripe.com/v1/balance) to determine whether a leaked key is
         *     still active. Never writes. Opt-in only — live calls against third-party
         *     APIs with found credentials carry legal and ToS implications.
         */
        post: operations["validateSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Trend history for a project */
        get: operations["getProjectHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/badge.svg": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Shields-style compliance badge */
        get: operations["getProjectBadge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rules */
        get: operations["listRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        /** Rule detail */
        get: operations["getRule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lint a rule YAML */
        post: operations["validateRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppressions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List suppressions */
        get: operations["listSuppressions"];
        put?: never;
        /** Create a suppression */
        post: operations["createSuppression"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/baselines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List baselines */
        get: operations["listBaselines"];
        put?: never;
        /** Create a baseline */
        post: operations["createBaseline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Severity: "critical" | "high" | "medium" | "low" | "info";
        /** @enum {string} */
        Category: "secrets" | "auth" | "injection" | "pii" | "crypto" | "logging" | "ratelimit" | "supplychain";
        /** @enum {string} */
        ScanStatus: "queued" | "running" | "completed" | "failed" | "canceled";
        /** @enum {string} */
        ScanSource: "upload" | "git" | "inline";
        /** @enum {string} */
        ScanTrigger: "manual" | "ci" | "webhook" | "schedule";
        /**
         * @description SARIF 2.1.0 `baselineState`, carried through unchanged.
         * @enum {string}
         */
        BaselineState: "new" | "unchanged" | "absent";
        /**
         * @description Secret findings only. Per the PRD, only `verified_live` flips the CI gate.
         * @enum {string}
         */
        Validity: "verified_live" | "inactive" | "unknown";
        /** @enum {string} */
        VerifierStatus: "pass" | "fail" | "escalated";
        /**
         * @description The gate *predicate*. Deliberately diverges from Snyk's own
         *     `all|upgradable|patchable`.
         *
         *     x-decision: D-003 — `fail_on` selects the predicate, `severity_threshold`
         *     sets the bar. The PRD's ANSI mockup conflates the two by printing
         *     `gate: fail-on=high`.
         * @enum {string}
         */
        FailOn: "all" | "new" | "verified-secrets";
        /**
         * @description `open` is the default — nobody has looked at it yet.
         *     `accepted` means a real problem, to be fixed.
         *     `dismissed` means not a problem here (a false positive).
         *     `suppressed` means real but deliberately not gating, and requires a reason.
         * @enum {string}
         */
        TriageState: "open" | "accepted" | "dismissed" | "suppressed";
        TriageUpdate: {
            triage_state: components["schemas"]["TriageState"];
            /** @description Required when moving to `dismissed` or `suppressed`. */
            reason?: string;
            /**
             * Format: date-time
             * @description Optional expiry, so a suppression gets revisited.
             */
            expires_at?: string | null;
        };
        /**
         * @description The closed vocabulary a quarantined model may choose from.
         * @enum {string}
         */
        FixAction: "env_lookup" | "parameterize_query" | "sanitize_input" | "add_auth_decorator" | "enforce_jwt_verify" | "redact_pii_log" | "tokenize_pan" | "upgrade_crypto" | "enforce_tls" | "add_rate_limit" | "add_idempotency_key" | "pin_or_remove_dep";
        Problem: {
            /**
             * Format: uri
             * @example https://sirius.dev/errors/rule-invalid
             */
            type?: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /**
             * @description Non-standard sixth member, `SIRIUS_ERR_*` namespace.
             * @example SIRIUS_ERR_RULE_SCHEMA
             * @example SIRIUS_ERR_PARSE
             */
            code?: string;
        };
        SeverityCounts: {
            critical?: number;
            high?: number;
            medium?: number;
            low?: number;
            info?: number;
        };
        ScanCreate: {
            /** Format: uuid */
            project_id: string;
            source?: components["schemas"]["ScanSource"];
            /** @example refs/pull/42/head */
            git_ref?: string;
            commit_sha?: string;
            baseline_commit?: string;
            /** @default false */
            diff_aware: boolean;
            /**
             * @example [
             *       "p/fintech-core",
             *       "p/secrets"
             *     ]
             */
            rulesets?: string[];
            /** Format: uuid */
            policy_id?: string;
            /** @default false */
            validate_secrets: boolean;
            /**
             * @description x-decision: D-002 — added to the PRD's body. The server echoes an
             *     `exit_code` on `scan.completed`, but the CLI computes its own gate
             *     verdict locally and treats the server value as a cross-check, so that
             *     CI behavior stays deterministic offline and under --replay.
             */
            severity_threshold?: components["schemas"]["Severity"];
            fail_on?: components["schemas"]["FailOn"];
        };
        Scan: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id?: string;
            status: components["schemas"]["ScanStatus"];
            source?: components["schemas"]["ScanSource"];
            trigger?: components["schemas"]["ScanTrigger"];
            git_ref?: string | null;
            commit_sha?: string | null;
            baseline_commit?: string | null;
            /** @example 72.5 */
            compliance_score?: number | null;
            /**
             * @description Scan-level aggregate over all findings, not just rendered ones.
             * @example 5120000
             */
            money_at_risk_inr?: number | null;
            counts?: components["schemas"]["SeverityCounts"];
            /** @enum {integer|null} */
            exit_code?: 0 | 1 | 2 | 3 | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        Finding: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            scan_id?: string;
            /** @example src/config.py */
            file: string;
            /** @example 14 */
            line: number;
            end_line?: number | null;
            /**
             * @description 1-indexed column of the offending token. Needed to align the `╰──`
             *     underline annotation in the CLI.
             *
             *     x-decision: D-005 — absent from the PRD's WebSocket `finding` frame
             *     though present in the DDL. Added to both here. Clients must degrade
             *     to an unaligned annotation when null.
             */
            col?: number | null;
            severity: components["schemas"]["Severity"];
            /** @example SIR-SEC-001 */
            rule_id: string;
            category: components["schemas"]["Category"];
            /**
             * @description Colon-namespaced clause references.
             * @example [
             *       "PCI-DSS:8.6.2",
             *       "RBI-DPSC",
             *       "DPDP:8"
             *     ]
             */
            compliance_ref?: string[];
            /** @example Hardcoded Stripe secret key */
            message: string;
            /**
             * @description Secret literals must arrive already truncated. Never transmit a full key.
             * @example STRIPE_KEY = "sk_live_51H8xR2eZv…"
             */
            snippet?: string | null;
            /** @description Stable hash for baseline diffing and dedup. Algorithm is server-side and TBD. */
            fingerprint?: string | null;
            baseline_state?: components["schemas"]["BaselineState"];
            validity?: components["schemas"]["Validity"];
            /** @example 4200000 */
            money_at_risk_inr?: number | null;
            /**
             * @description Derived from `triage_state == "suppressed"`. Never gates.
             * @default false
             */
            suppressed: boolean;
            triage_state?: components["schemas"]["TriageState"];
            fix_action?: components["schemas"]["FixAction"];
        };
        FindingPage: {
            items: components["schemas"]["Finding"][];
            next_cursor?: string | null;
            total?: number;
        };
        FixSuggestion: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            finding_id?: string;
            action: components["schemas"]["FixAction"];
            /** @example api_key */
            target?: string;
            /** @example 0.92 */
            confidence?: number;
            /**
             * @description Unified diff against the finding's **snippet**, not the whole file.
             *     Clients must re-locate the hunk by content rather than trusting the
             *     line number, since the file may have changed since the scan.
             *
             *     The example is the SIR-SEC-001 fix from the demo fixture, and matches
             *     contract/fixtures/chaos-repo/src/config.py line for line so that
             *     `sirius fix` works end to end against the mock.
             * @example @@ -14 +14 @@
             *     -STRIPE_KEY = "sk_live_51H8xR2eZvNOTAREALKE"
             *     +STRIPE_KEY = os.environ["STRIPE_API_KEY"]
             */
            diff: string;
            /** @description Template side-effects, e.g. an .env.example entry. */
            side_effects?: {
                /** @example .env.example */
                file?: string;
                /** @example STRIPE_API_KEY= */
                content?: string;
            }[];
            verifier_status: components["schemas"]["VerifierStatus"];
            /** @default false */
            escalate: boolean;
            /** Format: date-time */
            generated_at?: string;
        };
        Rule: {
            /** @example SIR-SEC-001 */
            id: string;
            version: string;
            enabled: boolean;
            category?: components["schemas"]["Category"];
            severity?: components["schemas"]["Severity"];
            message?: string;
            languages?: string[];
            compliance_ref?: string[];
            fix_action?: components["schemas"]["FixAction"];
            /** @example # sirius-ignore: SIR-SEC-001 */
            suppress_token?: string;
            yaml_body?: string;
        };
        SuppressionCreate: {
            /** Format: uuid */
            project_id: string;
            rule_id?: string;
            path_glob?: string;
            fingerprint?: string;
            /** @description Mandatory. */
            reason: string;
            /**
             * Format: date-time
             * @description ISO-8601, modeled on .snyk `expires`.
             */
            expires_at?: string | null;
        };
        Suppression: components["schemas"]["SuppressionCreate"] & {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            created_by?: string | null;
        };
        Baseline: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            project_id?: string;
            commit_sha?: string;
            fingerprints?: string[];
            /** Format: date-time */
            created_at?: string;
        };
        Report: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            scan_id?: string;
            /** @enum {string} */
            format?: "pdf" | "json" | "sarif";
            uri?: string;
            /** @description Detached JWS, ES256 over canonical JSON. */
            jws_signature?: string | null;
            /** Format: date-time */
            signed_at?: string | null;
            /** @description Inline report body for json format. */
            body?: Record<string, never>;
        };
        WsFrame: components["schemas"]["WsScanStarted"] | components["schemas"]["WsFileScanning"] | components["schemas"]["WsFinding"] | components["schemas"]["WsProgress"] | components["schemas"]["WsScanCompleted"] | components["schemas"]["WsError"];
        WsScanStarted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "scan.started";
            /** Format: uuid */
            scan_id: string;
            total_files: number;
            /** Format: date-time */
            ts?: string;
        };
        WsFileScanning: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "file.scanning";
            path: string;
            index: number;
            total: number;
        };
        WsFinding: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "finding";
            finding: components["schemas"]["Finding"];
        };
        WsProgress: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "progress";
            scanned: number;
            total: number;
            findings_so_far?: number;
        };
        WsScanCompleted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "scan.completed";
            /** @example 72.5 */
            compliance_score?: number;
            /** @example 5120000 */
            money_at_risk_inr?: number;
            counts: components["schemas"]["SeverityCounts"];
            /**
             * @description Server's gate verdict. Advisory — see D-002.
             * @enum {integer}
             */
            exit_code?: 0 | 1 | 2 | 3;
        };
        /** @description Per-file and non-fatal. Does not by itself change the exit code. */
        WsError: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /** @example SIRIUS_ERR_PARSE */
            code: string;
            path?: string;
            detail?: string;
        };
    };
    responses: {
        /** @description RFC-7807 problem detail */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ScanId: string;
        FindingId: string;
        Limit: number;
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listScans: {
        parameters: {
            query?: {
                project_id?: string;
                status?: components["schemas"]["ScanStatus"];
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Scan"][];
                        next_cursor?: string | null;
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    createScan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanCreate"];
            };
        };
        responses: {
            /** @description Scan queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    cancelScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Problem"];
        };
    };
    getScanResults: {
        parameters: {
            query?: {
                severity?: components["schemas"]["Severity"];
                category?: components["schemas"]["Category"];
                baseline_state?: components["schemas"]["BaselineState"];
                include_suppressed?: boolean;
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingPage"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getScanReport: {
        parameters: {
            query: {
                format: "pdf" | "json" | "sarif";
            };
            header?: never;
            path: {
                id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description The report. `json` and `sarif` are returned inline; `pdf` returns a
             *     download URI. The detached JWS (ES256 over canonical JSON) is in the
             *     `X-Sirius-Signature-JWS` header for inline formats.
             */
            200: {
                headers: {
                    /** @description Detached JWS signature over the canonical JSON body */
                    "X-Sirius-Signature-JWS"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                    "application/sarif+json": Record<string, never>;
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    requestFix: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ScanId"];
                fid: components["parameters"]["FindingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A fix suggestion (which may have failed verification) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixSuggestion"];
                };
            };
            404: components["responses"]["Problem"];
            /** @description Scan not complete, or a fix already applied */
            409: components["responses"]["Problem"];
        };
    };
    triageFinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ScanId"];
                fid: components["parameters"]["FindingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriageUpdate"];
            };
        };
        responses: {
            /** @description Updated finding */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    validateSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ScanId"];
                fid: components["parameters"]["FindingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validity determined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        validity: components["schemas"]["Validity"];
                        /** Format: date-time */
                        checked_at?: string;
                    };
                };
            };
            /** @description Rate limited */
            429: components["responses"]["Problem"];
        };
    };
    getProjectHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        scan_id?: string;
                        /** Format: date-time */
                        created_at?: string;
                        compliance_score?: number;
                        money_at_risk_inr?: number;
                        counts?: components["schemas"]["SeverityCounts"];
                    }[];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getProjectBadge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SVG badge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/svg+xml": string;
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listRules: {
        parameters: {
            query?: {
                ruleset?: string;
                category?: components["schemas"]["Category"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "SIR-SEC-001",
                     *         "version": "1",
                     *         "enabled": true,
                     *         "category": "secrets",
                     *         "severity": "critical",
                     *         "message": "Hardcoded payment-provider secret key",
                     *         "languages": [
                     *           "python",
                     *           "javascript",
                     *           "go"
                     *         ],
                     *         "compliance_ref": [
                     *           "PCI-DSS:8.6.2",
                     *           "RBI-DPSC",
                     *           "DPDP:8",
                     *           "CWE:798"
                     *         ],
                     *         "fix_action": "env_lookup",
                     *         "suppress_token": "# sirius-ignore: SIR-SEC-001"
                     *       },
                     *       {
                     *         "id": "SIR-SEC-002",
                     *         "version": "1",
                     *         "enabled": true,
                     *         "category": "secrets",
                     *         "severity": "high",
                     *         "message": "High-entropy string in source or config",
                     *         "languages": [
                     *           "python",
                     *           "javascript",
                     *           "go"
                     *         ],
                     *         "compliance_ref": [
                     *           "PCI-DSS:8.6.2",
                     *           "DPDP:8"
                     *         ],
                     *         "fix_action": "env_lookup",
                     *         "suppress_token": "# sirius-ignore: SIR-SEC-002"
                     *       },
                     *       {
                     *         "id": "SIR-SEC-010",
                     *         "version": "1",
                     *         "enabled": true,
                     *         "category": "injection",
                     *         "severity": "critical",
                     *         "message": "SQL built with string concatenation or formatting",
                     *         "languages": [
                     *           "python",
                     *           "javascript",
                     *           "go"
                     *         ],
                     *         "compliance_ref": [
                     *           "PCI-DSS:6.2.4",
                     *           "RBI-DPSC",
                     *           "CWE:89"
                     *         ],
                     *         "fix_action": "parameterize_query",
                     *         "suppress_token": "# sirius-ignore: SIR-SEC-010"
                     *       },
                     *       {
                     *         "id": "SIR-SEC-011",
                     *         "version": "1",
                     *         "enabled": true,
                     *         "category": "injection",
                     *         "severity": "critical",
                     *         "message": "OS command built from user input",
                     *         "languages": [
                     *           "python",
                     *           "javascript"
                     *         ],
                     *         "compliance_ref": [
                     *           "PCI-DSS:6.2.4",
                     *           "CWE:78"
                     *         ],
                     *         "fix_action": "sanitize_input",
                     *         "suppress_token": "# sirius-ignore: SIR-SEC-011"
                     *       },
                     *       {
                     *         "id": "SIR-SEC-020",
                     *         "version": "1",
                     *         "enabled": true,
                     *         "category": "auth",
                     *         "severity": "high",
                     *         "message": "Route missing an authentication decorator",
                     *         "languages": [
                     *           "python",
                     *           "javascript"
                     *         ],
                     *         "compliance_ref": [
                     *           "PCI-DSS:8.4.2",
                     *           "RBI-DPSC"
                     *         ],
                     *         "fix_action": "add_auth_decorator",
                     *         "suppress_token": "# sirius-ignore: SIR-SEC-020"
                     *       },
                     *       {
                     *         "id": "SIR-SEC-021",
                     *         "version": "1",
                     *         "enabled": true,
                     *         "category": "auth",
                     *         "severity": "critical",
                     *         "message": "JWT decoded without signature verification",
                     *         "languages": [
                     *           "python",
                     *           "javascript",
                     *           "go"
                     *         ],
                     *         "compliance_ref": [
                     *           "PCI-DSS:8.4.2",
                     *           "PCI-DSS:8.3.1",
                     *           "RBI-DPSC"
                     *         ],
                     *         "fix_action": "enforce_jwt_verify",
                     *         "suppress_token": "# sirius-ignore: SIR-SEC-021"
                     *       },
                     *       {
                     *         "id": "SIR-SEC-030",
                     *         "version": "1",
                     *         "enabled": true,
                     *         "category": "logging",
                     *         "severity": "high",
                     *         "message": "PAN, Aadhaar, or other PII written to logs",
                     *         "languages": [
                     *           "python",
                     *           "javascript",
                     *           "go"
                     *         ],
                     *         "compliance_ref": [
                     *           "PCI-DSS:3.4.1",
                     *           "DPDP:8",
                     *           "GDPR:Art.5"
                     *         ],
                     *         "fix_action": "redact_pii_log",
                     *         "suppress_token": "# sirius-ignore: SIR-SEC-030"
                     *       },
                     *       {
                     *         "id": "SIR-SEC-031",
                     *         "version": "1",
                     *         "enabled": true,
                     *         "category": "pii",
                     *         "severity": "critical",
                     *         "message": "Full PAN stored unmasked",
                     *         "languages": [
                     *           "python",
                     *           "javascript"
                     *         ],
                     *         "compliance_ref": [
                     *           "PCI-DSS:3.5.1",
                     *           "PCI-DSS:3.4.1",
                     *           "RBI-DPSC"
                     *         ],
                     *         "fix_action": "tokenize_pan",
                     *         "suppress_token": "# sirius-ignore: SIR-SEC-031"
                     *       },
                     *       {
                     *         "id": "SIR-SEC-040",
                     *         "version": "1",
                     *         "enabled": true,
                     *         "category": "crypto",
                     *         "severity": "high",
                     *         "message": "Weak hash, ECB mode, or a static initialization vector",
                     *         "languages": [
                     *           "python",
                     *           "javascript",
                     *           "go"
                     *         ],
                     *         "compliance_ref": [
                     *           "PCI-DSS:6.2.4",
                     *           "PCI-DSS:3.6.1",
                     *           "RBI-DPSC"
                     *         ],
                     *         "fix_action": "upgrade_crypto",
                     *         "suppress_token": "# sirius-ignore: SIR-SEC-040"
                     *       },
                     *       {
                     *         "id": "SIR-SEC-041",
                     *         "version": "1",
                     *         "enabled": true,
                     *         "category": "crypto",
                     *         "severity": "high",
                     *         "message": "Cardholder data sent over plain HTTP",
                     *         "languages": [
                     *           "python",
                     *           "javascript",
                     *           "go"
                     *         ],
                     *         "compliance_ref": [
                     *           "PCI-DSS:4.2.1",
                     *           "RBI-DPSC"
                     *         ],
                     *         "fix_action": "enforce_tls",
                     *         "suppress_token": "# sirius-ignore: SIR-SEC-041"
                     *       },
                     *       {
                     *         "id": "SIR-SEC-050",
                     *         "version": "1",
                     *         "enabled": true,
                     *         "category": "ratelimit",
                     *         "severity": "medium",
                     *         "message": "Money-movement endpoint without a rate limit",
                     *         "languages": [
                     *           "python",
                     *           "javascript"
                     *         ],
                     *         "compliance_ref": [
                     *           "PCI-DSS:6.2.4",
                     *           "RBI-DPSC"
                     *         ],
                     *         "fix_action": "add_rate_limit",
                     *         "suppress_token": "# sirius-ignore: SIR-SEC-050"
                     *       },
                     *       {
                     *         "id": "SIR-SEC-051",
                     *         "version": "1",
                     *         "enabled": true,
                     *         "category": "ratelimit",
                     *         "severity": "medium",
                     *         "message": "Money-movement POST without an idempotency key",
                     *         "languages": [
                     *           "python",
                     *           "javascript"
                     *         ],
                     *         "compliance_ref": [],
                     *         "fix_action": "add_idempotency_key",
                     *         "suppress_token": "# sirius-ignore: SIR-SEC-051"
                     *       },
                     *       {
                     *         "id": "SIR-SEC-060",
                     *         "version": "1",
                     *         "enabled": true,
                     *         "category": "supplychain",
                     *         "severity": "high",
                     *         "message": "Dependency runs an install script or ships obfuscated code",
                     *         "languages": [
                     *           "python",
                     *           "javascript"
                     *         ],
                     *         "compliance_ref": [
                     *           "PCI-DSS:6.3.2"
                     *         ],
                     *         "fix_action": "pin_or_remove_dep",
                     *         "suppress_token": "# sirius-ignore: SIR-SEC-060"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Rule"][];
                };
            };
        };
    };
    getRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "SIR-SEC-001",
                     *       "version": "1",
                     *       "enabled": true,
                     *       "category": "secrets",
                     *       "severity": "critical",
                     *       "message": "Hardcoded payment-provider secret key",
                     *       "languages": [
                     *         "python",
                     *         "javascript",
                     *         "go"
                     *       ],
                     *       "compliance_ref": [
                     *         "PCI-DSS:8.6.2",
                     *         "RBI-DPSC",
                     *         "DPDP:8",
                     *         "CWE:798"
                     *       ],
                     *       "fix_action": "env_lookup",
                     *       "suppress_token": "# sirius-ignore: SIR-SEC-001",
                     *       "yaml_body": "rule:\n  id: SIR-SEC-001\n  category: secrets\n  severity: critical\n  languages: [python, javascript, go]\n  message: \"Hardcoded payment-provider secret key detected.\"\n  metadata:\n    compliance:\n      pci_dss: [\"8.6.2\"]\n      rbi_dpsc: [\"card-payment-security\"]\n      dpdp: [\"8\"]\n    cwe: [\"CWE-798\"]\n    money_at_risk_model: \"provider_key\"\n    remediation_action: env_lookup\n  match:\n    kind: ast + regex\n    patterns:\n      - regex: '(sk_live_[0-9a-zA-Z]{24,}|rk_live_[0-9a-zA-Z]{24,})'\n      - entropy: { min_bits: 3.5 }\n    validity_check:\n      provider: stripe\n      method: GET\n      endpoint: \"https://api.stripe.com/v1/balance\"\n  fix:\n    action: env_lookup\n    target: api_key\n  suppress: \"# sirius-ignore: SIR-SEC-001\"\n"
                     *     }
                     */
                    "application/json": components["schemas"]["Rule"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    validateRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    yaml_body: string;
                };
            };
        };
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        valid: boolean;
                        errors?: {
                            path?: string;
                            message?: string;
                        }[];
                    };
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    listSuppressions: {
        parameters: {
            query?: {
                project_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suppression"][];
                };
            };
        };
    };
    createSuppression: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuppressionCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suppression"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    listBaselines: {
        parameters: {
            query?: {
                project_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Baseline"][];
                };
            };
        };
    };
    createBaseline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    project_id: string;
                    commit_sha: string;
                    /**
                     * Format: uuid
                     * @description Take fingerprints from this scan. Fingerprints are computed server-side; the CLI has no engine.
                     */
                    scan_id?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Baseline"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        version?: string;
                    };
                };
            };
            /** @description Unhealthy */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
