import {
  Project,
  Scan,
  Finding,
  ComplianceFramework,
  MoneyAtRisk,
  AttackPath,
  FixResult,
  Report,
  Rule,
  Integration,
  Notification,
  WorkspaceSettings,
} from '@sirius/types';


export const MOCK_PROJECTS: Project[] = [
  {
    id: 'prj-finsec-core-01',
    name: 'finsec-core-gateway',
    repositoryUrl: 'https://github.com/finsec/core-gateway.git',
    branch: 'main',
    lastScanId: 'scan-109283',
    lastScanTimestamp: new Date(Date.now() - 3600000).toISOString(),
    complianceScore: 94,
    moneyAtRiskUSD: 1450000,
    openFindingsCount: { critical: 1, high: 2, medium: 4, low: 8, info: 12 },
    createdAt: '2026-01-15T08:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prj-vault-service-02',
    name: 'key-vault-service',
    repositoryUrl: 'https://github.com/finsec/key-vault.git',
    branch: 'release/v2.4',
    lastScanId: 'scan-109284',
    lastScanTimestamp: new Date(Date.now() - 7200000).toISOString(),
    complianceScore: 88,
    moneyAtRiskUSD: 3800000,
    openFindingsCount: { critical: 2, high: 5, medium: 1, low: 3, info: 5 },
    createdAt: '2026-02-01T10:30:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prj-auth-service-03',
    name: 'identity-auth-service',
    repositoryUrl: 'https://github.com/finsec/auth-service.git',
    branch: 'main',
    lastScanId: 'scan-109285',
    lastScanTimestamp: new Date(Date.now() - 14400000).toISOString(),
    complianceScore: 98,
    moneyAtRiskUSD: 0,
    openFindingsCount: { critical: 0, high: 0, medium: 2, low: 4, info: 6 },
    createdAt: '2026-02-10T14:15:00Z',
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_SCANS: Scan[] = [
  {
    id: 'scan-109283',
    projectId: 'prj-finsec-core-01',
    status: 'completed',
    progress: {
      phase: 'completed',
      percentComplete: 100,
      filesScanned: 1420,
      totalFiles: 1420,
      findingsFound: 27,
      elapsedTimeMs: 42300,
    },
    startedAt: new Date(Date.now() - 3600000).toISOString(),
    completedAt: new Date(Date.now() - 3557700).toISOString(),
    durationMs: 42300,
    commitHash: 'a8f3b29c9d7e',
    initiatedBy: 'sarah.jenkins@finsec.io',
    summary: {
      totalFindings: 27,
      critical: 1,
      high: 2,
      medium: 4,
      low: 8,
      info: 12,
      moneyAtRiskUSD: 1450000,
      complianceScore: 94,
    },
  },
  {
    id: 'scan-109284',
    projectId: 'prj-vault-service-02',
    status: 'completed',
    progress: {
      phase: 'completed',
      percentComplete: 100,
      filesScanned: 890,
      totalFiles: 890,
      findingsFound: 16,
      elapsedTimeMs: 28400,
    },
    startedAt: new Date(Date.now() - 7200000).toISOString(),
    completedAt: new Date(Date.now() - 7171600).toISOString(),
    durationMs: 28400,
    commitHash: 'f4e21908',
    initiatedBy: 'alex.rivera@finsec.io',
    summary: {
      totalFindings: 16,
      critical: 2,
      high: 5,
      medium: 1,
      low: 3,
      info: 5,
      moneyAtRiskUSD: 3800000,
      complianceScore: 88,
    },
  },
  {
    id: 'scan-109282',
    projectId: 'prj-finsec-core-01',
    status: 'completed',
    progress: {
      phase: 'completed',
      percentComplete: 100,
      filesScanned: 1412,
      totalFiles: 1412,
      findingsFound: 31,
      elapsedTimeMs: 44100,
    },
    startedAt: new Date(Date.now() - 86400000).toISOString(),
    completedAt: new Date(Date.now() - 86355900).toISOString(),
    durationMs: 44100,
    commitHash: '9910c2ab',
    initiatedBy: 'system',
    summary: {
      totalFindings: 31,
      critical: 2,
      high: 3,
      medium: 5,
      low: 9,
      info: 12,
      moneyAtRiskUSD: 2900000,
      complianceScore: 89.5,
    },
  },
];

export const MOCK_FINDINGS: Finding[] = [
  {
    id: 'fnd-88219',
    scanId: 'scan-109283',
    projectId: 'prj-finsec-core-01',
    ruleId: 'SEC-JWT-004',
    title: 'Hardcoded JWT Signing Private Key in Auth Middleware',
    description: 'A static RSA private key was detected in code. Attackers could forge valid session tokens for any tenant.',
    severity: 'critical',
    status: 'open',
    category: 'secret_leak',
    filePath: 'src/middleware/auth.ts',
    startLine: 42,
    endLine: 58,
    codeSnippet: 'const PRIVATE_KEY = "-----BEGIN RSA PRIVATE KEY-----\\nMIIEowIBAAKCAQEA...";',
    moneyAtRiskUSD: 1450000,
    secretValidity: {
      status: 'valid',
      lastCheckedAt: new Date().toISOString(),
      provider: 'Internal KeyStore',
    },
    baselineState: 'new',
    triageHistory: [
      { id: 'th-1', timestamp: new Date(Date.now() - 3600000).toISOString(), action: 'opened', actor: 'FinSec Engine Bot', notes: 'Initial detection in Scan 8F31' },
    ],
    remediationGuidance: 'Rotate the compromised key pair immediately and load secrets from Environment KMS.',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'fnd-88220',
    scanId: 'scan-109283',
    projectId: 'prj-finsec-core-01',
    ruleId: 'FIN-PCI-603',
    title: 'Unencrypted Account PAN Payload Transmission',
    description: 'Primary Account Number (PAN) logged in plain text without tokenization.',
    severity: 'high',
    status: 'open',
    category: 'compliance_violation',
    filePath: 'src/services/payment.ts',
    startLine: 104,
    endLine: 112,
    codeSnippet: 'logger.info(`Processing card transaction: ${payload.cardNumber}`);',
    moneyAtRiskUSD: 0,
    remediationGuidance: 'Apply Vault Tokenization before writing transaction payloads to log output streams.',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'fnd-88221',
    scanId: 'scan-109284',
    projectId: 'prj-vault-service-02',
    ruleId: 'SEC-KMS-009',
    title: 'Weak Master Encryption Key Rotation Policy',
    description: 'Master KMS Key rotation interval exceeds PCI-DSS 4.0 requirement of 365 days.',
    severity: 'critical',
    status: 'open',
    category: 'crypto_flaw',

    filePath: 'config/kms.json',
    startLine: 12,
    endLine: 18,
    codeSnippet: '"rotationIntervalDays": 730',
    moneyAtRiskUSD: 3800000,
    remediationGuidance: 'Update rotationIntervalDays to 365 or enable AWS KMS automatic annual key rotation.',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_MONEY_AT_RISK: MoneyAtRisk = {
  totalUSD: 5250000,
  criticalUSD: 3800000,
  highUSD: 1450000,
  mediumUSD: 0,
  breakdownByFindingId: {
    'fnd-88219': 1450000,
    'fnd-88221': 3800000,
  },
  trendHistory: [
    { timestamp: '2026-08-10T00:00:00Z', amountUSD: 8400000 },
    { timestamp: '2026-08-14T00:00:00Z', amountUSD: 6100000 },
    { timestamp: '2026-08-17T00:00:00Z', amountUSD: 5250000 },
  ],
};

export const MOCK_COMPLIANCE_FRAMEWORKS: ComplianceFramework[] = [
  {
    id: 'pci-dss-4.0',
    name: 'PCI-DSS 4.0 Standard',
    version: '4.0',
    overallScore: 94,
    passedCount: 47,
    failedCount: 3,
    totalCount: 50,
    references: [
      {
        frameworkId: 'pci-dss-4.0',
        section: '6.3.2',
        requirementTitle: 'Software Architecture Vulnerability Prevention',
        status: 'non_compliant',
        associatedFindingIds: ['fnd-88219'],
      },
    ],
  },
  {
    id: 'soc2-type2',
    name: 'SOC2 Type II Security',
    version: '2026',
    overallScore: 96,
    passedCount: 32,
    failedCount: 1,
    totalCount: 33,
    references: [],
  },
];

export const MOCK_ATTACK_PATHS: AttackPath[] = [
  {
    id: 'ap-001',
    projectId: 'prj-finsec-core-01',
    title: 'Exposed Provider Credential to Payment Ledger Exfiltration',
    description: 'An attacker with repository access extracts hardcoded provider credentials in auth middleware, issues forged JWT administrative claims, accesses internal transaction APIs, and modifies financial ledgers.',
    severity: 'critical',
    entryNodeId: 'node-entry-cred',
    targetNodeId: 'node-asset-ledger',
    entryLabel: 'Exposed Provider Credential',
    targetLabel: 'Financial Payment Ledger',
    nodeCount: 5,
    findingCount: 2,
    financialExposureUSD: 1450000,
    estimatedExploitabilityScore: 9.8,
    findingIds: ['fnd-88219', 'fnd-88220'],
    nodes: [
      { id: 'node-entry-cred', label: 'Exposed Provider Credential', type: 'credential', findingId: 'fnd-88219', severity: 'critical', x: 80, y: 160 },
      { id: 'node-finding-jwt', label: 'Hardcoded Provider Signing Key', type: 'finding', findingId: 'fnd-88219', severity: 'critical', x: 280, y: 160 },
      { id: 'node-service-auth', label: 'Auth Gateway Middleware', type: 'service', x: 480, y: 160 },
      { id: 'node-endpoint-pay', label: 'Unauthorized Transaction API', type: 'endpoint', findingId: 'fnd-88220', severity: 'high', x: 680, y: 160 },
      { id: 'node-asset-ledger', label: 'Financial Payment Ledger DB', type: 'database', assetId: 'ast-ledger', x: 880, y: 160 },
    ],
    edges: [
      { id: 'edge-1', sourceNodeId: 'node-entry-cred', targetNodeId: 'node-finding-jwt', relationship: 'contains secret', riskWeight: 0.95 },
      { id: 'edge-2', sourceNodeId: 'node-finding-jwt', targetNodeId: 'node-service-auth', relationship: 'bypasses auth', riskWeight: 0.98 },
      { id: 'edge-3', sourceNodeId: 'node-service-auth', targetNodeId: 'node-endpoint-pay', relationship: 'grants API access', riskWeight: 0.96 },
      { id: 'edge-4', sourceNodeId: 'node-endpoint-pay', targetNodeId: 'node-asset-ledger', relationship: 'modifies ledger data', riskWeight: 0.99 },
    ],
  },
  {
    id: 'ap-002',
    projectId: 'prj-finsec-core-01',
    title: 'KMS Annual Key Rotation Violation to Customer Vault Access',
    description: 'Expired annual key rotation policy allows unauthorized decryption of archived customer financial records.',
    severity: 'high',
    entryNodeId: 'node-kms-policy',
    targetNodeId: 'node-vault-db',
    entryLabel: 'KMS Key Rotation Policy',
    targetLabel: 'Archived Customer Vault DB',
    nodeCount: 4,
    findingCount: 1,
    financialExposureUSD: 3800000,
    estimatedExploitabilityScore: 7.6,
    findingIds: ['fnd-88221'],
    nodes: [
      { id: 'node-kms-policy', label: 'KMS Key Rotation Policy', type: 'entry', findingId: 'fnd-88221', severity: 'high', x: 120, y: 320 },
      { id: 'node-finding-kms', label: 'AWS KMS Key Rotation Violation', type: 'finding', findingId: 'fnd-88221', severity: 'high', x: 340, y: 320 },
      { id: 'node-service-kms', label: 'AWS KMS Key Management Service', type: 'service', x: 560, y: 320 },
      { id: 'node-vault-db', label: 'Archived Customer Vault DB', type: 'database', assetId: 'ast-vault', x: 780, y: 320 },
    ],
    edges: [
      { id: 'edge-5', sourceNodeId: 'node-kms-policy', targetNodeId: 'node-finding-kms', relationship: 'violates policy', riskWeight: 0.8 },
      { id: 'edge-6', sourceNodeId: 'node-finding-kms', targetNodeId: 'node-service-kms', relationship: 'retains stale key', riskWeight: 0.85 },
      { id: 'edge-7', sourceNodeId: 'node-service-kms', targetNodeId: 'node-vault-db', relationship: 'decrypts vault', riskWeight: 0.9 },
    ],
  },
];


export const MOCK_FIX_RESULTS: Record<string, FixResult> = {
  'fnd-88219': {
    id: 'fix-99102',
    findingId: 'fnd-88219',
    pipelineId: 'pipe-c102',
    status: 'pending_review',
    originalCode: 'const PRIVATE_KEY = "-----BEGIN RSA PRIVATE KEY-----\\n...";',
    proposedCode: 'const PRIVATE_KEY = process.env.AUTH_RSA_PRIVATE_KEY;',
    diff: '- const PRIVATE_KEY = "-----BEGIN RSA PRIVATE KEY-----\\n...";\n+ const PRIVATE_KEY = process.env.AUTH_RSA_PRIVATE_KEY;',
    pullRequestUrl: 'https://github.com/finsec/core-gateway/pull/402',
    createdBranch: 'cerebus/fix-jwt-key-leak',
    verificationPassed: true,
  },
};

export const MOCK_REPORTS: Report[] = [
  {
    id: 'rep-8812',
    projectId: 'prj-finsec-core-01',
    scanId: 'scan-109283',
    type: 'executive',
    title: 'Executive Financial Security & Posture Audit Q3 2026',
    status: 'ready',
    format: 'pdf',
    generatedAt: new Date(Date.now() - 86400000).toISOString(),
    createdBy: 'Shivam Pandey (Lead DevSecOps)',
    downloadUrl: '/api/v1/reports/rep-8812/download',
    verificationStatus: 'verified',
    summary: {
      overallScore: 72.5,
      totalFindings: 43,
      criticalCount: 3,
      highCount: 12,
      mediumCount: 28,
      moneyAtRiskUSD: 1450000,
      passedControlsCount: 35,
      failedControlsCount: 13,
    },
    verification: {
      isVerified: true,
      signature: '0x8f3b29c9d7e41a9...8c2',
      verifiedAt: new Date(Date.now() - 86000000).toISOString(),
      verifierCertificate: 'FinSec Security Assurance CA-2026',
    },
  },
  {
    id: 'rep-8813',
    projectId: 'prj-finsec-core-01',
    scanId: 'scan-109283',
    type: 'technical',
    title: 'Technical Security & SARIF Evidence Assessment',
    status: 'ready',
    format: 'sarif',
    generatedAt: new Date(Date.now() - 43200000).toISOString(),
    createdBy: 'Shivam Pandey (Lead DevSecOps)',
    downloadUrl: '/api/v1/reports/rep-8813/download',
    verificationStatus: 'verified',
    summary: {
      overallScore: 72.5,
      totalFindings: 43,
      criticalCount: 3,
      highCount: 12,
      mediumCount: 28,
      moneyAtRiskUSD: 1450000,
      passedControlsCount: 35,
      failedControlsCount: 13,
    },
    verification: {
      isVerified: true,
      signature: '0x3a992d194e8201a...99b',
      verifiedAt: new Date(Date.now() - 43000000).toISOString(),
      verifierCertificate: 'FinSec Security Assurance CA-2026',
    },
  },
  {
    id: 'rep-8814',
    projectId: 'prj-finsec-core-01',
    scanId: 'scan-109283',
    type: 'compliance',
    title: 'PCI DSS 4.0 & SOC 2 Compliance Audit Evidence',
    status: 'ready',
    format: 'pdf',
    frameworkId: 'pci-dss-4.0',
    generatedAt: new Date(Date.now() - 21600000).toISOString(),
    createdBy: 'FinSec Automated Compliance Engine',
    downloadUrl: '/api/v1/reports/rep-8814/download',
    verificationStatus: 'verified',
    summary: {
      overallScore: 72.5,
      totalFindings: 43,
      criticalCount: 3,
      highCount: 12,
      mediumCount: 28,
      moneyAtRiskUSD: 1450000,
      passedControlsCount: 35,
      failedControlsCount: 13,
    },
    verification: {
      isVerified: true,
      signature: '0x7b1192e49a02931...71c',
      verifiedAt: new Date(Date.now() - 21500000).toISOString(),
      verifierCertificate: 'FinSec Security Assurance CA-2026',
    },
  },
];


export const MOCK_RULES: Rule[] = [
  {
    id: 'SEC-JWT-004',
    code: 'SEC-JWT-004',
    name: 'Hardcoded Cryptographic Secret',
    category: 'secret_leak',
    severity: 'critical',
    description: 'Detects hardcoded RSA/ECDSA/AES cryptographic keys in application source code.',
    isEnabled: true,
  },
];

export const MOCK_INTEGRATIONS: Integration[] = [
  {
    id: 'int-01',
    name: 'GitHub Cloud & Enterprise',
    type: 'github',
    category: 'source_control',
    description: 'Repository AST scanning, PR inline comments, and commit status checks.',
    status: 'connected',
    configuredAt: '2026-01-15T08:00:00Z',
    lastSyncAt: new Date(Date.now() - 3600000).toISOString(),
    config: {
      repository: 'finsec/core-gateway',
      apiTokenMasked: '••••••••••••••••••••••••3A9F',
    },
  },
  {
    id: 'int-02',
    name: 'GitLab Security Pipeline',
    type: 'gitlab',
    category: 'source_control',
    description: 'GitLab CI security gate evaluation and merge request security widgets.',
    status: 'disconnected',
  },
  {
    id: 'int-03',
    name: 'Jira Software Security Triage',
    type: 'jira',
    category: 'ticketing',
    description: 'Automated ticket creation for critical findings with Cerebus remediation summaries.',
    status: 'connected',
    configuredAt: '2026-01-20T10:00:00Z',
    lastSyncAt: new Date(Date.now() - 7200000).toISOString(),
    config: {
      channel: 'SEC-PROJECT-KEY',
    },
  },
  {
    id: 'int-04',
    name: 'Slack DevSecOps Alerts',
    type: 'slack',
    category: 'messaging',
    description: 'Real-time notifications for critical vulnerabilities and scan gate failures.',
    status: 'connected',
    configuredAt: '2026-02-01T14:30:00Z',
    lastSyncAt: new Date(Date.now() - 1800000).toISOString(),
    config: {
      channel: '#security-alerts-prod',
      webhookUrlMasked: 'https://hooks.slack.com/services/••••••••••••/••••••••••••',
    },
  },
  {
    id: 'int-05',
    name: 'PagerDuty Incident Escalation',
    type: 'pagerduty',
    category: 'alerting',
    description: 'Immediate high-priority page triggers on money-at-risk critical breaches.',
    status: 'disconnected',
  },
  {
    id: 'int-06',
    name: 'GitHub Actions Security Gate',
    type: 'github_actions',
    category: 'cicd',
    description: 'Native CI/CD pipeline step failing builds on security policy violations.',
    status: 'connected',
    configuredAt: '2026-02-10T11:00:00Z',
    lastSyncAt: new Date(Date.now() - 900000).toISOString(),
    config: {
      severityThreshold: 'high',
    },
  },
];

export const MOCK_WORKSPACE_SETTINGS: WorkspaceSettings = {
  workspaceName: 'SIRIUS FinSec Command Center',
  defaultProjectId: 'prj-finsec-core-01',
  defaultBranch: 'main',
  timezone: 'UTC-5 (Eastern Time)',
  dateFormat: 'YYYY-MM-DD',
  apiEndpoint: 'https://api.finsec.dev/v1',
  environment: 'production',
  apiKeyMasked: '••••••••••••••••••••••••9A1F',
  connectionStatus: 'connected',
  latencyMs: 12,
  policy: {
    severityThreshold: 'high',
    failOn: 'verified-secrets',
  },
  notificationPreferences: {
    criticalAlerts: true,
    scanCompletion: true,
    complianceDegradation: true,
    securityBreach: true,
  },
};


export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-01',
    type: 'critical_finding',
    title: 'Critical Vulnerability Discovered',
    message: 'Hardcoded JWT Signing Private Key detected in finsec-core-gateway.',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    isRead: false,
  },
];
